config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]

  root "homes#index"

  get '/', to: "homes#index"
  get '/trips', to: "homes#index"
  get "/trips/:id", to: "homes#index"
  get "/about", to: "about#index"

  resources :favorite_trips, only: [:destroy]

  namespace :api do
    namespace :v1 do
      post "yelp/search", to: "yelp#search"
    end
  end

  namespace :api do
    namespace :v1 do
      resources :trips, only: [:show] do
        resources :favorite_trips, only: [:create]
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true

  mount_uploader :profile_photo, ProfilePhotoUploader

  has_many :favorite_trips
  has_many :trips, through: :favorite_trips
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @favorites = @user.trips
  end
end

app/views/users/show.html.erb
<div class="user-show-page">
  <div class="user-container">
    <h1>Account Information</h1>
    <div class="userprofilepic">
      <%= image_tag("#{@user.profile_photo.default}", class:"userprofilepic-img") %>
    </div>
    <div class="userinfo-container">
      <%= @user.email %>
    </div>
    <div class="userinfo-container">
      <%= @user.username %>
    </div>
    <div class="edit-account-link-container">
      <%= link_to "Edit Account Information", edit_user_registration_path %>
    </div>
  </div>

  <div class="favorites-container-parent">
    <h1>Favorite Trips</h1>
    <% @favorites.each do |favorite| %>
      <div class="favorites-container">
        <%= link_to "Remove Favorite", favorite_trip_path(id: current_user.id, trip_id: favorite.trip_id), method: :delete %>

        <% favorite.places.each do |place| %>
          <div class="favorite-trip">
  
            <%= place.name %>

          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>